### ISSUE TITLE
Enhancement: Add limit view subArray option for large store arrays

### ISSUE THREAD

**Issue by Ganasist** [RealScout/redux-infinite-scroll#25] opened 2016-11-03 13:31 UTC
A nice enhancement for infinite scroll would be to limit the size of the array the displaying component handles, in the event that the store array of items becomes extremely large.

Basically if there are hundreds of items in the store array, the presentational component would only be exposed to an array of say 10-20 items (configurable) at any given time. Scrolling would 'slide' this array along the store array in real time. If the user scrolled to the beginning of the array, nothing would update - basically no items to load. If the user scrolled to the end of the array then a backend request could occur, to populate more items until none were available.

In this manner the store array could grow to an unlimited length, but we'd be able to expose only a small section of it to our presentational component at any given time. Not sure how useful people would find such a feature, just throwing it out there.

**Comment by dcurletti** [comment] 2016-11-03 22:57
Thanks for the feedback.  Marking this as a duplicate of  issue #23

**Closed as completed by dcurletti** 2016-11-03 22:57 UTC
Labels: duplicate
